#!/usr/bin/env bash
# ==============================================================================
#  Runner for curated ocean downscaling product splitting by depth
#
#  This code was created by Isaac Brito-Morales
#  (ibrito@conservation.org)
# ==============================================================================

set -euo pipefail

# ==============================================================================
# Runner: submit the by-depth splitter as a single Slurm job.
#
# Notes:
#   - This mirrors /home/SB5/ocean_downscaling_products into:
#       /home/SB5/ocean_downscaling_products_bydepth
#     or, when MAX_DEPTH_M is set and OUT_ROOT is not, into:
#       /home/SB5/ocean_downscaling_products_depths
#   - Set GEOTIFF=yes to export the generated by-depth NetCDF tree to GeoTIFF
#     after the split job completes successfully.
#   - The main tool script carries the HPC resource requests.
#   - This runner remains lightweight and only handles submission/logging.
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_SCRIPT="${SCRIPT_DIR}/../../tools/split_ocean_downscaling_products_by_depth.sh"
GEOTIFF_TOOL_SCRIPT="${SCRIPT_DIR}/../../tools/export_ocean_downscaling_products_to_geotiff.sh"
LOG_DIR="/home/sandbox-sparc/cesmle-ocn-fetch/logs"

IN_ROOT="${IN_ROOT:-/home/SB5/ocean_downscaling_products}"
MAX_DEPTH_M="${MAX_DEPTH_M:-}"
MAX_DEPTH_M_LOWER="${MAX_DEPTH_M,,}"
if [[ -z "${OUT_ROOT:-}" ]]; then
  if [[ -n "${MAX_DEPTH_M}" && "${MAX_DEPTH_M_LOWER}" != "all" ]]; then
    OUT_ROOT="/home/SB5/ocean_downscaling_products_depths"
  else
    OUT_ROOT="/home/SB5/ocean_downscaling_products_bydepth"
  fi
fi
TMP_DIR="${TMP_DIR:-${OUT_ROOT}/tmp_split_bydepth}"
MIN_DECIMALS="${MIN_DECIMALS:-3}"
INTEGER_WIDTH="${INTEGER_WIDTH:-4}"
COPY_2D_FILES="${COPY_2D_FILES:-yes}"

GEOTIFF="${GEOTIFF:-no}"
GEOTIFF_LOWER="${GEOTIFF,,}"
case "${GEOTIFF_LOWER}" in
  yes|true|1) GEOTIFF="yes" ;;
  no|false|0) GEOTIFF="no" ;;
  *)
    echo "ERROR: GEOTIFF must be yes/no or true/false"
    exit 1
    ;;
esac
GEOTIFF_OUT_ROOT="${GEOTIFF_OUT_ROOT:-${OUT_ROOT}_geotiff}"
GEOTIFF_OVERWRITE="${GEOTIFF_OVERWRITE:-${OVERWRITE:-no}}"
GEOTIFF_CPUS_PER_TASK="${GEOTIFF_CPUS_PER_TASK:-5}"

mkdir -p "${LOG_DIR}"

if [[ ! -x "${TOOL_SCRIPT}" ]]; then
  echo "ERROR: Tool script not found or not executable: ${TOOL_SCRIPT}"
  exit 1
fi

if [[ ! -d "${IN_ROOT}" ]]; then
  echo "ERROR: IN_ROOT does not exist: ${IN_ROOT}"
  exit 1
fi

if [[ "${GEOTIFF}" == "yes" && ! -x "${GEOTIFF_TOOL_SCRIPT}" ]]; then
  echo "ERROR: GeoTIFF tool script not found or not executable: ${GEOTIFF_TOOL_SCRIPT}"
  exit 1
fi

echo "Submitting curated ocean product by-depth split job:"
echo "IN ROOT          : ${IN_ROOT}"
echo "OUT ROOT         : ${OUT_ROOT}"
echo "MAX DEPTH M      : ${MAX_DEPTH_M:-<all>}"
echo "COPY 2D FILES    : ${COPY_2D_FILES}"
echo "GEOTIFF          : ${GEOTIFF}"
if [[ "${GEOTIFF}" == "yes" ]]; then
  echo "GEOTIFF OUT ROOT : ${GEOTIFF_OUT_ROOT}"
  echo "GEOTIFF OVERWRITE: ${GEOTIFF_OVERWRITE}"
fi

jid=$(
  sbatch --parsable \
    --export=ALL,IN_ROOT="${IN_ROOT}",OUT_ROOT="${OUT_ROOT}",TMP_DIR="${TMP_DIR}",MAX_DEPTH_M="${MAX_DEPTH_M}",MIN_DECIMALS="${MIN_DECIMALS}",INTEGER_WIDTH="${INTEGER_WIDTH}",COPY_2D_FILES="${COPY_2D_FILES}" \
    "${TOOL_SCRIPT}"
)

echo "  submitted as jobid=${jid}"

if [[ "${GEOTIFF}" == "yes" ]]; then
  geotiff_jid=$(
    sbatch --parsable \
      --dependency="afterok:${jid}" \
      --job-name="tif_depths" \
      --output="${LOG_DIR}/geotiff_depths_%j.out" \
      --error="${LOG_DIR}/geotiff_depths_%j.err" \
      --cpus-per-task="${GEOTIFF_CPUS_PER_TASK}" \
      --export=ALL,IN_ROOT="${OUT_ROOT}",OUT_ROOT="${GEOTIFF_OUT_ROOT}",OVERWRITE="${GEOTIFF_OVERWRITE}",NPROC="${GEOTIFF_CPUS_PER_TASK}" \
      "${GEOTIFF_TOOL_SCRIPT}"
  )
  echo "  submitted GeoTIFF export as jobid=${geotiff_jid} afterok:${jid}"
fi

echo "Done."
