#!/usr/bin/env bash
# ==============================================================================
#  Runner for curated ocean downscaling product splitting by depth
#
#  This code was created by Isaac Brito-Morales
#  (ibrito@conservation.org)
# ==============================================================================

set -euo pipefail

# ==============================================================================
# Runner: submit the by-depth splitter as Slurm jobs by subtree.
#
# Notes:
#   - This mirrors each selected subtree of /home/SB5/ocean_downscaling_products into:
#       /home/SB5/ocean_downscaling_products_bydepth
#     or, when MAX_DEPTH_M is set and OUT_ROOT is not, into:
#       /home/SB5/ocean_downscaling_products_depths
#   - Set GEOTIFF=yes to export the generated by-depth NetCDF tree to GeoTIFF
#     after the split job completes successfully.
#   - The main tool script carries the HPC resource requests.
#   - This runner remains lightweight and only handles discovery/submission/logging.
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_SCRIPT="${SCRIPT_DIR}/../../tools/split_ocean_downscaling_products_by_depth.sh"
GEOTIFF_TOOL_SCRIPT="${SCRIPT_DIR}/../../tools/export_ocean_downscaling_products_to_geotiff.sh"
LOG_DIR="/home/sandbox-sparc/cesmle-ocn-fetch/logs"

IN_ROOT="${IN_ROOT:-/home/SB5/ocean_downscaling_products}"
MAX_DEPTH_M="${MAX_DEPTH_M:-}"
MAX_DEPTH_M_LOWER="${MAX_DEPTH_M,,}"
if [[ -z "${OUT_ROOT:-}" ]]; then
  if [[ -n "${MAX_DEPTH_M}" && "${MAX_DEPTH_M_LOWER}" != "all" ]]; then
    OUT_ROOT="/home/SB5/ocean_downscaling_products_depths"
  else
    OUT_ROOT="/home/SB5/ocean_downscaling_products_bydepth"
  fi
fi
TMP_DIR="${TMP_DIR:-${OUT_ROOT}/tmp_split_bydepth}"
MIN_DECIMALS="${MIN_DECIMALS:-3}"
INTEGER_WIDTH="${INTEGER_WIDTH:-4}"
COPY_2D_FILES="${COPY_2D_FILES:-yes}"
FUTURE_MODELS="${FUTURE_MODELS:-auto}"
EXCLUDE_FUTURE_MODELS="${EXCLUDE_FUTURE_MODELS:-}"
EXCLUDE_NODES="${EXCLUDE_NODES:-${SBATCH_EXCLUDE:-}}"
read -r -a FUTURE_MODEL_LIST <<< "${FUTURE_MODELS}"
read -r -a EXCLUDE_FUTURE_MODEL_LIST <<< "${EXCLUDE_FUTURE_MODELS}"

GEOTIFF="${GEOTIFF:-no}"
GEOTIFF_LOWER="${GEOTIFF,,}"
case "${GEOTIFF_LOWER}" in
  yes|true|1) GEOTIFF="yes" ;;
  no|false|0) GEOTIFF="no" ;;
  *)
    echo "ERROR: GEOTIFF must be yes/no or true/false"
    exit 1
    ;;
esac
GEOTIFF_OUT_ROOT="${GEOTIFF_OUT_ROOT:-${OUT_ROOT}_geotiff}"
GEOTIFF_OVERWRITE="${GEOTIFF_OVERWRITE:-${OVERWRITE:-no}}"
GEOTIFF_CPUS_PER_TASK="${GEOTIFF_CPUS_PER_TASK:-5}"

mkdir -p "${LOG_DIR}"

if [[ ! -x "${TOOL_SCRIPT}" ]]; then
  echo "ERROR: Tool script not found or not executable: ${TOOL_SCRIPT}"
  exit 1
fi

if [[ ! -d "${IN_ROOT}" ]]; then
  echo "ERROR: IN_ROOT does not exist: ${IN_ROOT}"
  exit 1
fi

if [[ "${GEOTIFF}" == "yes" && ! -x "${GEOTIFF_TOOL_SCRIPT}" ]]; then
  echo "ERROR: GeoTIFF tool script not found or not executable: ${GEOTIFF_TOOL_SCRIPT}"
  exit 1
fi

contains_word() {
  local needle="$1"
  shift
  local candidate

  for candidate in "$@"; do
    [[ "${candidate}" == "${needle}" ]] && return 0
  done
  return 1
}

include_subtree() {
  local subtree="$1"
  local rel_path model

  rel_path="${subtree#${IN_ROOT}/}"
  case "${rel_path}" in
    baseline/*)
      return 0
      ;;
    future/*)
      model="${rel_path#future/}"
      model="${model%%/*}"
      if [[ -n "${EXCLUDE_FUTURE_MODELS}" ]] && contains_word "${model}" "${EXCLUDE_FUTURE_MODEL_LIST[@]}"; then
        return 1
      fi
      if [[ "${FUTURE_MODELS}" != "auto" ]] && ! contains_word "${model}" "${FUTURE_MODEL_LIST[@]}"; then
        return 1
      fi
      return 0
      ;;
    *)
      return 0
      ;;
  esac
}

mapfile -t SUBTREES < <(
  while IFS= read -r subtree; do
    include_subtree "${subtree}" && printf '%s\n' "${subtree}"
  done < <({
    find "${IN_ROOT}/baseline" -mindepth 1 -maxdepth 1 -type d ! -name 'tmp*' 2>/dev/null
    find "${IN_ROOT}/future" -mindepth 1 -maxdepth 1 -type d ! -name 'tmp*' 2>/dev/null
  } | sort)
)
if (( ${#SUBTREES[@]} == 0 )); then
  echo "ERROR: No baseline/future split subtrees found under: ${IN_ROOT}"
  exit 1
fi

echo "Submitting curated ocean product by-depth split jobs by subtree:"
echo "IN ROOT          : ${IN_ROOT}"
echo "OUT ROOT         : ${OUT_ROOT}"
echo "MAX DEPTH M      : ${MAX_DEPTH_M:-<all>}"
echo "COPY 2D FILES    : ${COPY_2D_FILES}"
echo "FUTURE MODELS    : ${FUTURE_MODELS}"
echo "EXCLUDE FUTURE   : ${EXCLUDE_FUTURE_MODELS:-<none>}"
echo "EXCLUDE NODES    : ${EXCLUDE_NODES:-<none>}"
echo "GEOTIFF          : ${GEOTIFF}"
if [[ "${GEOTIFF}" == "yes" ]]; then
  echo "GEOTIFF OUT ROOT : ${GEOTIFF_OUT_ROOT}"
  echo "GEOTIFF OVERWRITE: ${GEOTIFF_OVERWRITE}"
fi

sbatch_args=()
if [[ -n "${EXCLUDE_NODES}" ]]; then
  sbatch_args+=(--exclude="${EXCLUDE_NODES}")
fi

for subtree in "${SUBTREES[@]}"; do
  rel_path="${subtree#${IN_ROOT}/}"
  out_subtree="${OUT_ROOT}/${rel_path}"
  tmp_subtree="${TMP_DIR}/${rel_path}"
  job_tag="$(echo "${rel_path}" | tr '/' '_' | tr -cd '[:alnum:]_')"

  jid=$(
    sbatch --parsable \
      "${sbatch_args[@]}" \
      --job-name="split_${job_tag}" \
      --output="${LOG_DIR}/split_bydepth_${job_tag}_%j.out" \
      --error="${LOG_DIR}/split_bydepth_${job_tag}_%j.err" \
      --export=ALL,IN_ROOT="${subtree}",OUT_ROOT="${out_subtree}",TMP_DIR="${tmp_subtree}",MAX_DEPTH_M="${MAX_DEPTH_M}",MIN_DECIMALS="${MIN_DECIMALS}",INTEGER_WIDTH="${INTEGER_WIDTH}",COPY_2D_FILES="${COPY_2D_FILES}",FUTURE_MODELS="${FUTURE_MODELS}",EXCLUDE_FUTURE_MODELS="${EXCLUDE_FUTURE_MODELS}" \
      "${TOOL_SCRIPT}"
  )
  echo "  submitted SUBTREE=${rel_path} as jobid=${jid}"

  if [[ "${GEOTIFF}" == "yes" ]]; then
    geotiff_out_subtree="${GEOTIFF_OUT_ROOT}/${rel_path}"
    geotiff_jid=$(
      sbatch --parsable \
        --dependency="afterok:${jid}" \
        --job-name="tifD_${job_tag}" \
        "${sbatch_args[@]}" \
        --output="${LOG_DIR}/geotiff_depths_${job_tag}_%j.out" \
        --error="${LOG_DIR}/geotiff_depths_${job_tag}_%j.err" \
        --cpus-per-task="${GEOTIFF_CPUS_PER_TASK}" \
        --export=ALL,IN_ROOT="${out_subtree}",OUT_ROOT="${geotiff_out_subtree}",OVERWRITE="${GEOTIFF_OVERWRITE}",NPROC="${GEOTIFF_CPUS_PER_TASK}",FUTURE_MODELS="${FUTURE_MODELS}",EXCLUDE_FUTURE_MODELS="${EXCLUDE_FUTURE_MODELS}" \
        "${GEOTIFF_TOOL_SCRIPT}"
    )
    echo "  submitted GeoTIFF export SUBTREE=${rel_path} as jobid=${geotiff_jid} afterok:${jid}"
  fi
done

echo "Done."
